name: Terraform Apply

concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: false

on:
  push:
    branches: [ develop, test, main ]

jobs:
  terraform-apply:
    runs-on: windows-latest
    permissions:
      contents: read

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Apply (Dev Environment)
        run: |
          for dir in users groups; do
            terraform -chdir=tfprojects/env/dev/$dir init
            terraform -chdir=tfprojects/env/dev/$dir apply -auto-approve
          done
        shell: bash
